{% set name = "lcr_genie" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/neilswainston/LCRGenie/archive/refs/tags/{{ version }}.tar.gz
  sha256: 0284cb51394134a1db9b921168e379fd4c6ae5c7bccf40bf95e8f1b1d9c1abae

build:
  number: 0
  script: {{ PYTHON }} -m pip install -vv .
  noarch: python

requirements:
  host:
    - python =3.7
    - pip
  run:
    - python =3.7
    - biopython
    - openpyxl
    - pandas
    - requests
    - pysbol2

test:
  source_files:
    - tests
  imports:
    - lcr_genie
  requires:
    - pytest
  commands:
    - python -m lcr_genie --help
    - python -m pytest -v

about:
  home: https://github.com/neilswainston/LCRGenie/
  summary: Ligase Chain Reaction
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - breakthewall
    - kenza12
